SELECT YEAR(TRANSACTION_DATE) ||
CASE
WHEN (CAST (MONTH(TRANSACTION_DATE) AS int) < 10)
THEN '0' || CAST(MONTH(TRANSACTION_DATE) AS int)
ELSE CAST (MONTH(TRANSACTION_DATE) AS char(2))
END AS YEAR_MONTH_REP,
BUYER_COUNTY AS COUNTY,
DECIMAL(SUM(DOSAGE_UNIT),31,2) AS MONTHLY_COUNTS,
DECIMAL(AVG(SUM(DOSAGE_UNIT)) 
    OVER (ORDER BY YEAR(TRANSACTION_DATE), MONTH(TRANSACTION_DATE) ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), 31, 2) AS SMOOTH_COUNTS
FROM CSE532.DEA_NY
WHERE BUYER_COUNTY = 'SUFFOLK'
GROUP BY YEAR(TRANSACTION_DATE), BUYER_COUNTY, MONTH(TRANSACTION_DATE);