WITH QUERY_RES (BUYER_ZIP, SUM_OF_MME)
AS (
    SELECT BUYER_ZIP, SUM(MME) AS SUM_OF_MME
    FROM CSE532.DEA_NY
    GROUP BY BUYER_ZIP
)
SELECT BUYER_ZIP AS CONSUMER_ZIP, SUM_OF_MME / ZIP_CODE_TABLE.POP AS NORMALIZED_MME, RANK() OVER (ORDER BY SUM_OF_MME / ZIP_CODE_TABLE.POP DESC) AS POS
FROM QUERY_RES
INNER JOIN CSE532.ZIP AS ZIP_CODE_TABLE
ON BUYER_ZIP = ZIP_CODE_TABLE.ZIP
WHERE ZIP_CODE_TABLE.POP IS NOT NULL
AND ZIP_CODE_TABLE.POP > 0
LIMIT 10;