SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;

WITH NEIGHBORING_ZIPCODE (SHAPE, ZIPCODE) AS (
    SELECT Z1.SHAPE, Z1.ZIPCODE
    FROM CSE532.ZIPCODE_TABLE AS Z1
    WHERE db2gse.ST_Intersects(
        Z1.SHAPE, (
            SELECT Z2.SHAPE
            FROM CSE532.ZIPCODE_TABLE AS Z2
            WHERE Z2.ZIPCODE = '11735'
        )
    ) = TRUE
)
SELECT DISTINCT (T.FACILITY_NAME), N.ZIPCODE
FROM CSE532.TRIFacility AS T, NEIGHBORING_ZIPCODE AS N
WHERE db2gse.ST_Within(T.LOCATION_DATA, N.SHAPE);

SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;